adoceana/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("usuarios.urls")), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Using the URLconf defined in adoceana.urls, Django tried these URL patterns, in this order:admin/auth/^static/(?P<path>.*)$The empty path didn’t match any of these.

usuarios/urls.py
from django.urls import path, include
from django.contrib.auth.models import User
from . import views 
from .views import cad_produto

app_name = 'usuarios'

urlpatterns = [
    path('', views.index, name='index'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('login/', views.entrar, name="login"),
    path('catalogo/', views.catalogo, name="catalogo"),
    path('cad_produto/', views.cad_produto, name="cad_produto"),
    path('comprar/<int:id>', views.comprar, name="comprar"),
    path('catalogo/cad_produto.html', cad_produto, name='cad_produto'),
]

usuarios/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Usuario (models.Model):
    nome = models.CharField("Nome", max_length=50)
    telefone = models.CharField("Telefone", max_length=11)
    acesso = models.OneToOneField(User, on_delete=models.CASCADE)


from django.db import models

class Produto(models.Model):
    img = models.ImageField(upload_to='produtos/')
    titulo = models.CharField(max_length=255)
    descricao = models.TextField()
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    qtd = models.PositiveIntegerField()

    def __str__(self):
        return self.titulo

usuarios/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import Usuario,Produto
from django.contrib.auth import logout,authenticate,login
from django.contrib import messages

from django.contrib.auth.models import User
def cadastro(request):
    if request.method == "POST":
        nome = request.POST.get('username')
        email = request.POST.get('email')
        telefone = request.POST.get('tel')
        senha = request.POST.get('password')
        user = Usuario.objects.filter(acesso__username=email).first() 
        acesso = User.objects.filter(email = email).first()
        #return HttpResponse(username)#
        if user is None and acesso is None:
            usuario = Usuario(nome=nome, telefone=telefone)
            acesso = User.objects.create_user(username=email, email=email, password=senha)
            acesso.is_active = True
            acesso.is_staff = True
            acesso.save()
            acesso
            usuario.acesso = acesso
            usuario.save()
            return redirect("usuarios:login")
        elif user is not None:
            messages.error(request, 'Erro: já existe usuário com esse email cadastrado')
        elif acesso is not None:
            messages.error(request, 'Erro: já existe acesso com esse email cadastrado')
        return render(request, 'cadastro.html')
    else:
        
        return render(request, 'cadastro.html')
            
                 

def entrar(request):
    if request.POST:
        email = request.POST.get("email_or_username")
        senha = request.POST.get("password")
        usu = authenticate(username=email, password=senha)

        if usu:
            print('conseguiu autenticar')
            login(request,usu)
            return redirect("usuarios:catalogo")
            
        else:
            print('n conseguiu autenticar',usu, email, senha, teste)
            return redirect("usuarios:login")
        
    return render(request, 'login.html')

#@login_required(login_url="usuarios:login")
def index(request):
    return render(request, 'index.html')

@login_required(login_url="usuarios:login")
def catalogo(request):
    lista = Produto.objects.all()
    return render(request, 'catalogo.html', {'lista':lista})

#@login_required(login_url="usuarios:login")
def cad_produto(request):

    return render(request, 'cad_produto.html')

def comprar(request, id):

    return render(request, 'final.compra.html', {'produto_id': id})

def final_compra(request, produto_id):
    return render(request, 'usuarios/final.compra.html')

usuarios/templates/cad.produto.html
{% extends 'index.html' %}

{% block title %}: Novo{% endblock %}

{% block content %}    
    <div class="container">
        <h1>Cadastrar Produto</h1>
        <form action="{% url 'cad.produto' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            <label for="nome">Nome do Produto:</label>
            <input type="text" id="nome" name="nome" required/>
            
            <label for="descricao">Descrição do Produto:</label>
            <input type="text" id="descricao" name="descricao" required/>
            
            <label for="valor">Valor:</label>
            <input type="number" id="valor" name="valor" required/>
            
            <label for="imagem">Imagem:</label>
            <input type="file" id="imagem" name="imagem" accept="image/*" required/>
            
            <input type="submit" value="Cadastrar"/>
        </form>
    </div>
{% endblock %}

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background: url("{% static 'imagens/tela-de-fundo.jpg' %}") center center fixed; /* Substitua 'sua-imagem-de-fundo.jpg' pelo caminho da sua imagem */
        background-size: cover;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .container {
        width: 300px;
        background-color: #E5D69D;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px #656A41(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
        color: #656A41;
    }

    label {
        display: block;
        margin: 10px 0 5px;
        color: #656A41;
    }

    input {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        box-sizing: border-box;
    }

    input[type="submit"] {
        background-color: #656A41;
        color: #fff;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #656A41;
    }
</style>

usuarios/templates/cad_produto.html
{% load static %}
<!DOCTYPE html>
<html lang="en">   
    <div class="container">
        <h1>Cadastrar Produto</h1>
        <form action="{% url 'usuarios:cad_produto' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            
            
            <label for="nome">Nome do Produto:</label>
            <input type="text" id="nome" name="nome" required/>
            
            <label for="descricao">Descrição do Produto:</label>
            <input type="text" id="descricao" name="descricao" required/>
            
            <label for="valor">Valor:</label>
            <input type="number" id="valor" name="valor" required/>
            
            <label for="imagem">Imagem:</label>
            <input type="file" id="imagem" name="imagem" accept="image/*" required/>
            
            <input type="submit" value="Cadastrar"/>
        </form>
    </div>

<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background: url("{%static 'imagens/tela-de-fundo.jpg' %}") center center fixed; /* Substitua 'sua-imagem-de-fundo.jpg' pelo caminho da sua imagem */
        background-size: cover;
        display: flex;
        justify-content: center;
        align-items: center;
        height: 100vh;
    }

    .container {
        width: 300px;
        background-color: #E5D69D;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 10px #656A41(0, 0, 0, 0.1);
    }

    h1 {
        text-align: center;
        color: #656A41;
    }

    label {
        display: block;
        margin: 10px 0 5px;
        color: #656A41;
    }

    input {
        width: 100%;
        padding: 8px;
        margin-bottom: 10px;
        box-sizing: border-box;
    }

    input[type="submit"] {
        background-color: #656A41;
        color: #fff;
        cursor: pointer;
    }

    input[type="submit"]:hover {
        background-color: #656A41;
    }
</style>

usuarios/templates/cadastro.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: url("{%static 'imagens/tela-de-fundo.jpg'%}") center center fixed; /* Substitua 'sua-imagem-de-fundo.jpg' pelo caminho da sua imagem */
            background-size: cover;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            width: 300px;
            background-color: #E5D69D;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px #656A41(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #656A41;
        }

        label {
            display: block;
            margin: 10px 0 5px;
            color: #656A41;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            box-sizing: border-box;
        }

        input[type="submit"] {
            background-color: #656A41;
            color: #fff;
            cursor: pointer;
        }

        input[type="submit"]:hover {
            background-color: #656A41;
        }

        .login-link {
            text-align: center;
            margin-top: 10px;
        }

        .login-link a {
            color: #656A41;
            text-decoration: none;
        }

        .login-link a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Cadastro</h2>
        {% if messages %}       
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form method="POST" action="#">
            {% csrf_token %}
            <label for="username">Nome:</label>
            <input type="text" id="username" name="username" required>

            <label for="tel">Telefone:</label>
            <input type="tel" id="tel" name="tel" required>

            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required>

            <label for="password">Senha:</label>
            <input type="password" id="password" name="password" required>

            <label for="confirm_password">Confirmar senha:</label>
            <input type="password" id="confirm_password" name="confirm_password" required>

            <input type="submit" value="Cadastrar">
        </form>

        <div class="login-link">
            <a href="{%url 'usuarios:login' %}">Voltar para o Login</a>
        </div>
    </div>
</body>
</html>

usuarios/templates/carrinho.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Carrinho de Compras</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: url('tela-de-fundo.jpg') center center fixed;
            background-size: cover;
        }

        header {
            background-color: #E5D69D;
            color: #656A41;
            text-align: center;
            padding: 1em;
        }

        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }

        .cart-item {
            background-color: #FFFFFF;
            padding: 1em;
            margin: 1em 0;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        footer {
            background-color: #E5D69D;
            color: #656A41;
            text-align: center;
            padding: 1em 0;
            position: absolute;
            bottom: 0;
            width: 100%;
        }
    </style>
</head>
<body>

    <header>
        <h1>Carrinho de Compras</h1>
    </header>

    <div class="container">
        <div class="cart-item">
            <h3>Produto 1</h3>
            <p>Descrição do Produto 1.</p>
            <p>R$ 19,99</p>
            <button>Remover</button>
        </div>

        <div class="cart-item">
            <h3>Produto 2</h3>
            <p>Descrição do Produto 2.</p>
            <p>R$ 29,99</p>
            <button>Remover</button>
        </div>

        <!-- Adicione mais itens conforme necessário -->

        <div class="total">
            <h3>Total:</h3>
            <p>R$ 49,98</p>
        </div>
    </div>

    <footer>
        <p>&copy; 2023 Adoce Ana</p>
    </footer>

    <script>
        function removerItem(itemId) {
            var item = document.getElementById(itemId);
            item.parentNode.removeChild(item);
        }
    </script>

</body>
</html>

usuarios/templates/catalogo.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Catálogo de Produtos</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: url("{% static 'imagens/tela-de-fundo.jpg' %}") center center fixed; 
            background-size: cover;
            position: relative;
        }

        header {
            background-color: #E5D69D;
            color: #656A41;
            text-align: center;
            padding: 1em;
            position: relative;
            z-index: 1; /* Cabeçalho esteja acima do plano de fundo */
        }

        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
            position: relative;
            z-index: 1; /* Produtos estejam acima do plano de fundo */
            display: flex;
            margin-bottom: 60px;
            flex-wrap: wrap; /* Permite que os produtos se movam para a próxima linha em telas menores */
            justify-content: space-around; /* Distribui uniformemente as divs */
        }

        .product {
            width: 20%;
            margin: 1%;
            background-color: #E5D69D;
            padding: 1em;
            box-sizing: border-box;
            border-radius: 8px;
            box-shadow: 0 0 10px #656A41(0, 0, 0, 0.1);
            text-align: center;
        }

        .product img {
            max-width: 100%;
            height: auto;
            border-radius: 4px; /* Adicionando borda arredondada nas imagens */
        }

        .product h3 {
            margin-top: 0;
        }

        .product-button,
        .product a,
        .product-button-cadastro {
            font-size: 16px;
            color:#fff;
            background-color: #656A41;
            border: none;
            padding: 8px 16px;
            border-radius: 4px;
            cursor: pointer;
            margin-left: 10px;
            text-decoration: none;
            display: inline-block;
            transition: background-color 0.3s;
        }

        .product-button:hover,
        .product a:hover,
        .product-button-cadastro {
            background-color: #E5D69D;
            color: #656A41;
        }

        footer {
            background-color: #E5D69D;
            color: #656A41;
            text-align: center;
            padding: 1em 0;
            position: fixed;
            bottom: 0;
            width: 100%;
            z-index: 1; /* Rodapé esteja acima do plano de fundo */
        }

        /* Ícone do carrinho */
        .cart-icon {
            position: absolute;
            top: 10px;
            right: 10px;
            font-size: 32px; /* Tamanho maior */
            color: #656A41;
            cursor: pointer;
            z-index: 2; /* Ícone do carrinho esteja acima do plano de fundo */
        }
    </style>
</head>
<body>

    <header>
        <h1>Catálogo de Produtos</h1>
        <!-- Ícone do carrinho -->
        <div class="cart-icon" onclick="location.href='carrinho.html'">&#128722;</div>
        <button class="=product-button" onclick="location.href='cad_produto.html'">Cadastro de Produto</button>
    </header>

    <div class="container">
        {%for p in lista %}
        <div class="product">
            <img src="/media/{{p.img}}" alt="Produto 1">
            <h3>{{p.titulo}}</h3>
            <p>{{p.descricao}}</p>
            <p>R$ {{p.valor}}</p>
            <a href="/comprar/{{p.id}}">Comprar</a>
        </div>
        {%endfor%}
    </div>

    <div style="height: 60px;"></div>

    <footer>
        <p>&copy; 2023 Adoce Ana</p>
    </footer>

</body>
</html>

usuarios/templates/final.compra.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Finalizar Compra</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: url("{%static 'imagens/tela-de-fundo.jpg'%}") center center fixed;
            background-size: cover;
            position: relative;
        }

        .container {
            max-width: 600px;
            margin: 180px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        h1 {
            text-align: center;
            color: #656A41;
        }

        .item {
            border-bottom: 1px solid #ddd;
            padding: 10px 0;
        }

        #quantidade-container {
            text-align: center;
        }

        #quantidade-btns button {
            font-size: 18px;
            padding: 5px 10px;
            background-color: #E5D69D;
            color: #656A41;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        .total {
            text-align: right;
            font-weight: bold;
            color: #656A41;
        }

        .options {
            text-align: center;
            margin-top: 20px;
        }

        .confirm-btn,
        .back-btn,
        .cancel-btn {
            padding: 10px 20px;
            margin: 0 10px;
            font-size: 14px;
            background-color: #E5D69D;
            color: #656A41;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }

        form {
            margin-top: 20px;
        }

        label {
            display: block;
            margin-bottom: 8px;
            color: #656A41;
        }

        input,
        select {
            width: 100%;
            padding: 8px;
            margin-bottom: 16px;
            box-sizing: border-box;
        }

        /* Adicionado uma classe oculta para esconder os campos de cartão de crédito, débito e Pix por padrão */
        .cartao-credito,
        .cartao-debito,
        .pix {
            display: none;
        }
    </style>
</head>

<body>
    <div class="container">
        <h1>Finalizar Compra</h1>

        <div class="item">
            <span>Copudim</span>
            <div id="quantidade-container">
                <button onclick="diminuirQuantidade()">-</button>
                <span id="quantidade">1</span>
                <button onclick="aumentarQuantidade()">+</button>
            </div>
            <span>Preço unitário: R$ 14,00</span>
        </div>

        <div class="total">
            <span>Total a Pagar: R$ <span id="total">14,00</span></span>
        </div>

        <form>
            <label for="nome">Nome:</label>
            <input type="text" id="nome" name="nome" required>

            <label for="endereco">Endereço:</label>
            <input type="text" id="endereco" name="endereco" required>

            <label for="formaPagamento">Forma de Pagamento:</label>
            <select id="formaPagamento" name="formaPagamento" onchange="mostrarCamposPagamento()">
                <option value="credito">Cartão de Crédito</option>
                <option value="debito">Cartão de Débito</option>
                <option value="pix">Pix</option>
                <option value="boleto">Boleto Bancário</option>
            </select>

            <div class="cartao-credito">
                <label for="numeroCartao">Número do Cartão de Crédito:</label>
                <input type="text" id="numeroCartao" name="numeroCartao">

                <label for="dataValidade">Data de Validade:</label>
                <input type="text" id="dataValidade" name="dataValidade">

                <label for="cvv">CVV:</label>
                <input type="text" id="cvv" name="cvv">
            </div>

            <div class="cartao-debito">
                <label for="numeroCartaoDebito">Número do Cartão de Débito:</label>
                <input type="text" id="numeroCartaoDebito" name="numeroCartaoDebito">

                <label for="dataValidadeDebito">Data de Validade:</label>
                <input type="text" id="dataValidadeDebito" name="dataValidadeDebito">

                <label for="cvvDebito">CVV do Cartão de Débito:</label>
                <input type="text" id="cvvDebito" name="cvvDebito">
            </div>

            <div class="pix">
                <label for="chavePix">Chave Pix:</label>
                <input type="text" id="chavePix" name="chavePix">
                <button onclick="gerarQrCode()">Gerar QR Code</button>
                <div id="qrcode"></div>
            </div>

            <div class="options">
                <!-- Adicionado o evento onclick para chamar a função confirmarCompra() -->
                <button class="confirm-btn" onclick="confirmarCompra()">Confirmar Compra</button>
                <button class="back-btn" onclick="voltarParaCatalogo()">Voltar para o Catálogo</button>
                <button class="cancel-btn">Cancelar Compra</button>
            </div>
        </form>

        <script>
            // Funções para manipular a quantidade do produto
            function aumentarQuantidade() {
                var quantidadeElemento = document.getElementById("quantidade");
                var quantidadeAtual = parseInt(quantidadeElemento.innerText);
                quantidadeElemento.innerText = quantidadeAtual + 1;
                atualizarTotal();
            }

            function diminuirQuantidade() {
                var quantidadeElemento = document.getElementById("quantidade");
                var quantidadeAtual = parseInt(quantidadeElemento.innerText);

                // Certifique-se de que a quantidade não seja menor que 1
                if (quantidadeAtual > 1) {
                    quantidadeElemento.innerText = quantidadeAtual - 1;
                    atualizarTotal();
                }
            }

            // Função para atualizar o total com base na quantidade
            function atualizarTotal() {
                var quantidade = parseInt(document.getElementById("quantidade").innerText);
                var precoUnitario = 14.00; // Preço unitário do produto
                var total = quantidade * precoUnitario;
                document.getElementById("total").innerText = total.toFixed(2); // Formatando para duas casas decimais
            }

            // Função para mostrar os campos de pagamento correspondentes
            function mostrarCamposPagamento() {
                var formaPagamento = document.getElementById("formaPagamento");
                var camposCartaoCredito = document.querySelector(".cartao-credito");
                var camposCartaoDebito = document.querySelector(".cartao-debito");
                var camposPix = document.querySelector(".pix");

                // Oculta todos os campos por padrão
                camposCartaoCredito.style.display = "none";
                camposCartaoDebito.style.display = "none";
                camposPix.style.display = "none";

                // Mostra os campos correspondentes à forma de pagamento selecionada
                if (formaPagamento.value === "credito") {
                    camposCartaoCredito.style.display = "block";
                } else if (formaPagamento.value === "debito") {
                    camposCartaoDebito.style.display = "block";
                } else if (formaPagamento.value === "pix") {
                    camposPix.style.display = "block";
                }
            }

            // Função para gerar QR Code
            function gerarQrCode() {
                var chavePix = document.getElementById("chavePix").value;
                var qrcode = new QRCode(document.getElementById("qrcode"), {
                    text: "chavepix:" + chavePix,
                    width: 128,
                    height: 128
                });
            }

            // Função para exibir o alerta ao confirmar a compra
            function confirmarCompra() {
                alert("Sua compra foi solicitada com sucesso!");
            }

            // Função para voltar para a página do catálogo
            function voltarParaCatalogo() {
                // Redireciona para a página "catalogo.html"
                window.location.href = 'catalogo.html';
    }
        </script>
    </div>
</body>

</html>

usuarios/templates/index.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Adoce Ana</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #656A41;
        }

        header {
            background-color: #E5D69D;
            color: #656A41;
            padding: 1em;
            text-align: center;
        }

        nav {
            background-color: #E5D69D;
            padding: 1em;
            text-align: center;
        }

        section {
            padding: 1em;
            text-align: center; /* Adicionado para centralizar o conteúdo */
        }

        footer {
            background-color: #E5D69D;
            color: #656A41;
            padding: 1em;
            text-align: center;
            position: fixed;
            bottom: 0;
            right: 0;
            left: 0;
        }

        .button-container {
            text-align: center;
            margin: 1em 0;
        }

        .button-container button {
            padding: 0.5em 1em;
            margin: 0 0.5em;
            font-size: 1em;
            cursor: pointer;
            /* Adicionando cores aos botões */
            background-color: #656A41; /* botão Login */
            color: white;
            border: none;
            border-radius: 5px;
        }

        .button-container button:hover {
            background-color: #E5D69D; /* Alterando a cor quando o botão é hover (passagem do mouse) */
        }

        .button-container button:nth-child(2) {
            background-color: #656A41; /*  botão Cadastro */
        }

        .button-container button:nth-child(2):hover {
            background-color: #E5D69D; /* Alterando a cor quando o botão é hover (passagem do mouse) */
        }
    </style>
</head>
<body>
    <header>
        <h1>Bem-vindo(a) a</h1>
    </header>

    <nav>
        <!-- Sua barra de navegação aqui, se necessário -->
    </nav>
    <section>
        <img src="{%static 'imagens/logo.png'%}" alt="Descrição da imagem">

        <div class="button-container">
            <button onclick="location.href={%url 'usuarios:login' %}">Login</button>
            <button onclick="location.href={%url 'usuarios:cadastro' %}">Cadastro</button>
        </div>
    </section>

    <footer>
        <p>&copy; 2023, Adoce Ana.</p>
    </footer>

</body>

</html>

usuarios/templates/login.html
{%load static%}
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background: url("{%static 'imagens/tela-de-fundo.jpg'%}") center center fixed; 
            background-size: cover;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            width: 300px;
            background-color: #E5D69D;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 0 10px #656A41(0, 0, 0, 0.1);
        }

        h2 {
            text-align: center;
            color: #656A41;
        }

        label {
            display: block;
            margin: 10px 0 5px;
            color: #555;
        }

        input {
            width: 100%;
            padding: 8px;
            margin-bottom: 10px;
            box-sizing: border-box;
        }

        input[type="submit"],
        input[type="button"] {
            background-color: #656A41;
            color: #fff;
            cursor: pointer;
        }

        input[type="submit"]:hover,
        input[type="button"]:hover {
            background-color: #656A41;
        }
    </style>
</head>
<body>
    <div class="container">
        <h2>Login</h2>
        {% if messages %}
        <hr/>
        <h1>Avisos:</h1>
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <label for="email_or_username">Email ou Nome de Usuário:</label>
            <input type="text" id="email_or_username" name="email_or_username" required>

            <label for="password">Senha:</label>
            <input type="password" id="password" name="password" required>

            <input type="submit" value="Login">
            <!--Botão de cadastro-->
        </form>
    </div>
</body>
</html>